import { IChat } from "@/interfaces/chat";

export const dummyChat: IChat[] = [
  {
    id: 133,
    assignee: "Yaya Jujura",
    isRead: true,
    chatDate: new Date().toISOString(),
    content: "siap pak, tidak masalah saya tunggu",
    recepient: "bpk. ahmad affas",
    senderName: "Yaya Jujura",
    type: "Customer",
    chatType: "TO",
    platform: "CRM Plus",
  },
  {
    id: 1322,
    assignee: "Yaya Jujura",
    isRead: true,
    chatDate: new Date().toISOString(),
    content:
      "Ok kemungkinan saya agak telat karna jalanan agak macet saya otw sekarang",
    recepient: "Yaya Jujura",
    senderName: "bpk. ahmad affas",
    type: "Customer",
    chatType: "FROM",
    platform: "Jujura",
  },
  {
    id: 133,
    assignee: "Yaya Jujura",
    isRead: true,
    chatDate: new Date().toISOString(),
    content: "dan materai 10rb, 3pcs pak",
    recepient: "bpk. ahmad affas",
    senderName: "Yaya Jujura",
    type: "Customer",
    chatType: "TO",
    platform: "CRM Plus",
  },
  {
    id: 133,
    assignee: "Yaya Jujura",
    isRead: true,
    chatDate: new Date().toISOString(),
    content: "Cukup KTP dan NPWP saja pak",
    recepient: "bpk. ahmad affas",
    senderName: "Yaya Jujura",
    type: "Customer",
    chatType: "TO",
    platform: "CRM Plus",
  },
  {
    id: 12,
    assignee: "Yaya Jujura",
    isRead: true,
    chatDate: new Date().toISOString(),
    content: "Ok. baik nanti saya kesana, dokumen yang diperlukan apa nggih?",
    recepient: "Yaya Jujura",
    senderName: "bpk. ahmad affas",
    type: "Customer",
    chatType: "FROM",
    platform: "Jujura",
  },
  {
    id: 1,
    assignee: "Yaya Jujura",
    isRead: true,
    chatDate: new Date().toISOString(),
    content: "Waalaikumsalam. Dikantor AMK pak jam 10.00 WIB",
    recepient: "bpk. ahmad affas",
    senderName: "Yaya Jujura",
    type: "Customer",
    chatType: "TO",
    platform: "CRM Plus",
  },
  {
    id: 3,
    assignee: "Yaya Jujura",
    isRead: true,
    chatDate: new Date().toISOString(),
    content:
      "Assalamulaikam bapak/ibu, untuk pembayaran akan dilaksanakan hari ini pukul berapa ya? dan lokasinya dimana?",
    recepient: "Yaya Jujura",
    senderName: "bpk. ahmad affas",
    type: "Customer",
    chatType: "FROM",
    platform: "Jujura",
  },
];
